import { Marked } from "marked";

const marked = new Marked({ gfm: true, breaks: false });

export function slugHeading(text) {
  return String(text).toLowerCase().trim().replace(/[^\w\s-]/g, "").replace(/\s+/g, "-").replace(/-+/g, "-");
}

export function splitFrontmatter(md) {
  const m = md.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?/);
  if (!m) return { frontmatter: null, body: md };
  const frontmatter = {};
  for (const line of m[1].split(/\r?\n/)) {
    const i = line.indexOf(":");
    if (i > 0) frontmatter[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return { frontmatter, body: md.slice(m[0].length) };
}

const WIKI_RE = /(!?)\[\[([^\]\n]+?)\]\]/g;

function parseInner(inner) {
  let [target, alias] = inner.split("|");
  alias = alias?.trim() || null;
  let heading = null;
  const hash = target.indexOf("#");
  if (hash >= 0) { heading = target.slice(hash + 1).trim() || null; target = target.slice(0, hash); }
  return { target: target.trim(), alias, heading };
}

export function extractWikilinks(md) {
  const out = [];
  const { body } = splitFrontmatter(md);
  for (const m of body.matchAll(WIKI_RE)) {
    const { target, alias, heading } = parseInner(m[2]);
    out.push({ target, alias, heading, embed: m[1] === "!" });
  }
  return out;
}

function esc(s) {
  return String(s).replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]));
}

const IMG_EXT = /\.(png|jpe?g|gif|webp|svg)$/i;

function preprocess(body, resolveLink, links) {
  // 1. strip %%comments%%
  let s = body.replace(/%%[\s\S]*?%%/g, "");
  // 2. wikilinks -> placeholder tokens (so marked does not mangle them)
  const tokens = [];
  s = s.replace(WIKI_RE, (_, bang, inner) => {
    const { target, alias, heading } = parseInner(inner);
    const r = resolveLink(target);
    const text = alias ?? (heading ? `${target} › ${heading}` : target);
    let html;
    if (bang === "!" && r.exists && IMG_EXT.test(target)) html = `<img class="embed" src="${esc(r.href)}" alt="${esc(target)}">`;
    else if (r.exists) html = `<a class="wikilink" href="${esc(r.href)}${heading ? "#" + slugHeading(heading) : ""}">${esc(text)}</a>`;
    else html = `<span class="wikilink missing">${esc(text)}</span>`;
    links.push({ target, alias, heading, embed: bang === "!" });
    tokens.push(html);
    return ` WL${tokens.length - 1} `;
  });
  // 3. highlights
  s = s.replace(/==([^=\n]+)==/g, "<mark>$1</mark>");
  // 4. tags (not inside URLs or headings)
  s = s.replace(/(^|\s)#([A-Za-z][\w/-]*)/g, (_, pre, tag) => `${pre}<a class="tag" href="/notes/search?q=${encodeURIComponent("#" + tag)}">#${esc(tag)}</a>`);
  // 5. callouts: "> [!type] Title" followed by "> body" lines
  s = s.replace(/^> \[!(\w+)\]([^\n]*)\n((?:>.*(?:\n|$))*)/gm, (_, type, title, rest) => {
    const bodyMd = rest.split("\n").map((l) => l.replace(/^>\s?/, "")).join("\n").trim();
    const inner = marked.parse(bodyMd);
    return `<div class="callout callout-${esc(type.toLowerCase())}"><div class="callout-title">${esc(title.trim() || type)}</div><div class="callout-body">${inner}</div></div>\n`;
  });
  return { s, tokens };
}

export function renderNote(md, { resolveLink }) {
  const normalized = md.replace(/\r\n/g, "\n");
  const { frontmatter, body } = splitFrontmatter(normalized);
  const links = [];
  // Escape ALL raw HTML from the note before markdown so nothing the note author
  // typed directly (script tags, event-handler attributes on img/a/div, etc.) can
  // ever reach the output as live markup. Every real HTML tag in the final output
  // (wikilinks, embeds, callouts, highlights) is generated by preprocess() below,
  // strictly after this escape runs, so there is nothing legitimate to whitelist here.
  const safe = body.replace(/</g, "&lt;");
  const { s, tokens } = preprocess(safe, resolveLink, links);
  let html = marked.parse(s);
  html = html.replace(/ WL(\d+) /g, (_, i) => tokens[Number(i)]);
  // marked emits GFM task-list checkboxes as <input checked="" disabled="" type="checkbox">
  // (attribute order: checked, disabled, type). Normalize to a stable attribute order
  // with type first so consumers can rely on `type="checkbox"` appearing before `checked`.
  html = html.replace(/<input([^>]*)>/g, (_, attrs) => {
    const checked = /\bchecked\b/.test(attrs) ? " checked" : "";
    const disabled = /\bdisabled\b/.test(attrs) ? " disabled" : "";
    return `<input type="checkbox"${checked}${disabled}>`;
  });
  return { html, frontmatter, links };
}
